services:
    redis:
        image: redis:alpine
        container_name: coursework-redis-group-13-tiic
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        networks:
            - app-network
        command: redis-server --appendonly yes --dir /data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5

    backend:
        build: ./backend
        container_name: coursework-backend-group-13-tiic
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=development
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            redis:
                condition: service_healthy
        networks:
            - app-network
        volumes:
            - ./backend:/app
            - /app/node_modules

    frontend:
        build: ./frontend
        container_name: coursework-frontend-group-13-tiic
        ports:
            - "5173:5173"
        depends_on:
            - backend
        networks:
            - app-network
        volumes:
            - ./frontend:/app
            - /app/node_modules
        environment:
            - VITE_API_URL=http://localhost:3000

volumes:
    redis-data:
        driver: local

networks:
    app-network:
        driver: bridge
